SET TERM ^ ;

CREATE OR ALTER FUNCTION CONTA_TEXTO (
    A_DS_FRASE DOM_VARCHAR255,
    A_DS_TEXTO DOM_VARCHAR32000)
RETURNS INTEGER
AS
DECLARE VARIABLE V_DIFERENCA DOM_INTEGER;
BEGIN
   IF ((A_DS_TEXTO IS NULL) OR (A_DS_FRASE IS NULL)) THEN
      RETURN 0;
   ELSE
      V_DIFERENCA = CHAR_LENGTH(A_DS_TEXTO) - CHAR_LENGTH(REPLACE(A_DS_TEXTO, A_DS_FRASE, ''));
      RETURN V_DIFERENCA / CHAR_LENGTH(A_DS_FRASE);
END^

SET TERM ; ^

/* Existing privileges on this procedure */

GRANT EXECUTE ON FUNCTION CONTA_TEXTO TO SYSDBA;