WITH ULTIMA_COMPRA
AS (SELECT
       N.CD_PESSOA CD_PESSOA, SUM(IT.VL_LIQUIDO) VL_LIQUIDO, SUM(IT.QT_ITEMNOTA) QT_ITEM
    FROM (SELECT
             N.CD_PESSOA, MAX(CAST(N.DT_EMISSAO || ' ' || N.HR_NOTA AS TIMESTAMP)) DT_ULT_NOTA
          FROM NOTA N
          WHERE N.TP_NOTA = 'S'
            AND N.ST_NOTA = 'V'
          GROUP BY 1) X
    INNER JOIN NOTA N ON (N.CD_PESSOA = X.CD_PESSOA
           AND CAST(N.DT_EMISSAO || ' ' || N.HR_NOTA AS TIMESTAMP) = X.DT_ULT_NOTA
           AND N.TP_NOTA = 'S'
           AND N.ST_NOTA = 'V')
    INNER JOIN ITEMNOTA IT ON (IT.CD_EMPRESA = N.CD_EMPRESA
           AND IT.NR_LANCAMENTO = N.NR_LANCAMENTO
           AND IT.TP_NOTA = N.TP_NOTA
           AND IT.CD_SERIE = N.CD_SERIE)
    GROUP BY CD_PESSOA

),

QUERY_PRICIPAL
AS (SELECT
       X.*,

       CASE
          WHEN SUM(PC_TOTAL) OVER(ORDER BY QT_MEDIO_6M DESC) <= 70.99 THEN 'A'
          WHEN SUM(PC_TOTAL) OVER(ORDER BY QT_MEDIO_6M DESC) <= 90.99 THEN 'B'
          WHEN SUM(PC_TOTAL) OVER(ORDER BY QT_MEDIO_6M DESC) >= 91.00 THEN 'C'
       END DS_CLASSIFICACAO
    FROM (SELECT
             COALESCE(PP.CD_PERFIL, P.CD_PESSOA) CD_PESSOA, COALESCE(PE.DS_PERFIL, P.NM_PESSOA) NM_PESSOA,
             CASE
                WHEN SUM(IT.QT_ITEMNOTA) >= 300 THEN 'Acima de 300 pneus'
                WHEN SUM(IT.QT_ITEMNOTA) BETWEEN 200 AND 299 THEN 'De 200 à 299 Pneus'
                WHEN SUM(IT.QT_ITEMNOTA) BETWEEN 100 AND 199 THEN 'De 100 à 199 Pneus'
                WHEN SUM(IT.QT_ITEMNOTA) BETWEEN 50 AND 99 THEN 'De 50 à 99 Pneus'
                WHEN SUM(IT.QT_ITEMNOTA) BETWEEN 30 AND 49 THEN 'De 30 à 49 Pneus'
                WHEN SUM(IT.QT_ITEMNOTA) BETWEEN 10 AND 29 THEN 'De 10 à 29 Pneus'
                WHEN SUM(IT.QT_ITEMNOTA) BETWEEN 01 AND 09 THEN 'De 01 à 9 Pneus'
                ELSE ''
             END DS_TIPO,
             (SUM(COALESCE(IT.QT_ITEMNOTA, 0)) / 6) QT_MEDIO_6M,
             SUM(UC.VL_LIQUIDO) / NULLIF(SUM(UC.QT_ITEM), 0) MEDIA_COMPRA,
             (SUM(COALESCE(IT.QT_ITEMNOTA, 0)) / 6) * 100 / SUM((SUM(COALESCE(IT.QT_ITEMNOTA, 0)) / 6)) OVER() PC_TOTAL,
             EXTRACT(MONTH FROM N.DT_EMISSAO) NR_MES, EXTRACT(YEAR FROM N.DT_EMISSAO) NR_ANO

          FROM NOTA N
          INNER JOIN ITEMNOTA IT ON (IT.CD_EMPRESA = N.CD_EMPRESA
                                 AND IT.NR_LANCAMENTO = N.NR_LANCAMENTO
                                 AND IT.TP_NOTA = N.TP_NOTA
                                 AND IT.CD_SERIE = N.CD_SERIE)
          INNER JOIN PESSOA P ON (P.CD_PESSOA = N.CD_PESSOA)
          LEFT JOIN PESSOAPERFIL PP ON (PP.CD_PESSOA = N.CD_PESSOA
                                    AND PP.CD_PERFIL BETWEEN 100 AND 105)
          LEFT JOIN PERFIL PE ON (PE.CD_PERFIL = PP.CD_PERFIL)
          INNER JOIN ITEM I ON (I.CD_ITEM = IT.CD_ITEM)
          INNER JOIN MOVIMENTACAO MOV ON (MOV.CD_MOVIMENTACAO = IT.CD_MOVIMENTACAO)
          INNER JOIN ULTIMA_COMPRA UC ON (UC.CD_PESSOA = N.CD_PESSOA)
          WHERE N.DT_EMISSAO BETWEEN :MONTH_BEGIN(-5,DATE) AND :MONTH_END(0,DATE)
            AND I.CD_GRUPO = 3
            AND N.TP_NOTA = 'S'
            AND N.ST_NOTA = 'V'
            AND MOV.CD_TIPOCONTA IS NOT NULL
            AND MOV.CD_OPERACAO IS NOT NULL
            AND MOV.ST_RECEITA = 'S'
          GROUP BY CD_PESSOA, NM_PESSOA, NR_MES, NR_ANO
          ORDER BY QT_MEDIO_6M DESC) X
    ORDER BY X.QT_MEDIO_6M DESC
    )

SELECT
   Q.DS_CLASSIFICACAO, COUNT(Q.DS_CLASSIFICACAO) QT_PARTICIPACAO, Q.NR_MES||'/'||Q.NR_ANO DS_DATA
FROM QUERY_PRICIPAL Q
GROUP BY Q.DS_CLASSIFICACAO, Q.NR_MES, Q.NR_ANO--, DS_DATA
ORDER BY Q.NR_ANO, Q.NR_MES