WITH FATURAMENTO_RNF009
AS (SELECT
       PV.CD_PESSOA || ' - ' || PV.NM_PESSOA DS_VENDEDOR, PV.CD_PESSOA CD_VENDEDOR, SUM(IT.VL_LIQUIDO) VL_LIQUIDO,
       SUM(IIF(I.CD_SUBGRUPO IN (105, 308), IT.QT_ITEMNOTA, 0)) QT_CONSERTO, SUM(IT.QT_ITEMNOTA) QT_ITEM,
       CAST((SUM(IT.VL_LIQUIDO) * 100) / SUM(SUM(IT.VL_LIQUIDO)) OVER () AS NUMERIC(15,2)) PC_PARTICIPACAO
    FROM NOTA N
    INNER JOIN ITEMNOTA IT ON (IT.CD_EMPRESA = N.CD_EMPRESA
           AND IT.NR_LANCAMENTO = N.NR_LANCAMENTO
           AND IT.TP_NOTA = N.TP_NOTA
           AND IT.CD_SERIE = N.CD_SERIE)
    INNER JOIN PESSOA PV ON (PV.CD_PESSOA = N.CD_VENDEDOR)
    INNER JOIN MOVIMENTACAO M ON (M.CD_MOVIMENTACAO = IT.CD_MOVIMENTACAO)
    INNER JOIN ITEM I ON (I.CD_ITEM = IT.CD_ITEM)
    WHERE N.DT_EMISSAO BETWEEN PRIMEIRODIAMES(CURRENT_DATE) AND ULTIMODIAMES(CURRENT_DATE)
      AND N.ST_NOTA = 'V'
      AND N.TP_NOTA = 'S'
      AND M.CD_TIPOCONTA IS NOT NULL
      AND M.CD_MOVIMENTACAO IN (7, 103)
    GROUP BY DS_VENDEDOR, PV.CD_PESSOA
)
SELECT
   X.DS_VENDEDOR, ABS(X.QT_CONSERTO - SUM(V.O_QT_ITEM)) QT_CONS_N_FAT, X.VL_LIQUIDO, X.PC_PARTICIPACAO,
   X.QT_ITEM
FROM FATURAMENTO_RNF009 X
LEFT JOIN VIEW_RRC012_E(' AND PP.IDEMPRESA  = 1
                     AND OPR.DTFECHAMENTO >= PRIMEIRODIAMES(CURRENT_DATE)
                     AND OPR.DTFECHAMENTO <= ULTIMODIAMES(CURRENT_DATE)
                     AND PP.IDVENDEDOR = '|| X.CD_VENDEDOR ||' ', 'WHERE 1=1 AND I.CD_SUBGRUPO IN (105) ', NULL, 'N') V ON (1 = 1)
GROUP BY X.DS_VENDEDOR, X.QT_CONSERTO, X.VL_LIQUIDO, X.PC_PARTICIPACAO, X.QT_ITEM