SET TERM ^ ;

CREATE OR ALTER FUNCTION PRIMEIRODIAMES (
    I_DT_ATUAL DOM_DATE)
RETURNS DOM_DATE
AS
BEGIN
   IF (I_DT_ATUAL IS NULL) THEN
      RETURN NULL;
   ELSE
      RETURN CAST('01.'||EXTRACT(MONTH FROM :I_DT_ATUAL)||'.'||EXTRACT(YEAR FROM :I_DT_ATUAL) AS DATE);
END^

SET TERM ; ^

/* Existing privileges on this procedure */

GRANT EXECUTE ON FUNCTION PRIMEIRODIAMES TO SYSDBA;