@ECHO OFF

PATH=%PATH%;"C:\Program Files\Firebird\Firebird_3_0"

SET BASEATUAL="localhost/3051:C:\Database\BASE_INCIAL.FDB"
SET BACKUP="C:\Database\BACKUP_BASE_INICIAL.FBK"
SET BASENOVA="localhost/3051:C:\Database\BASE_INICIAL_NOVA.FDB"

SET ISC_USER=SYSDBA	

SET ISC_PASSWORD=masterkey

ECHO VALIDANDO BANCO DE DADOS AGUARDE...
GFIX -V -FU %BASEATUAL%

ECHO PREPARANDO BANCO DE DADOS PARA BACKUP AGUARDE...
GFIX -M -I %BASEATUAL%

ECHO INICIANDO BACKUP DA BASE AGUARDE...
gbak -b -g -v -ig %BASEATUAL% %BACKUP%

ECHO RESTAURANDO BASE AGUARDE...
gbak -c -v %BACKUP% %BASENOVA%
