/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/


/* View: VIEW_SALESGRID */
CREATE OR ALTER VIEW VIEW_SALESGRID(
    NF_DATA,
    NF_NUMERO,
    NF_SERIE,
    NF_TIPO,
    NF_LANCAMENTO,
    CD_EMPRESA,
    CD_FILIAL,
    CD_ESTADO,
    CD_CENTRO_RESULTADO,
    CD_MUNICIPIO,
    CD_CLIENTE,
    CD_VENDEDOR,
    CD_PARCEIRO,
    CD_SUPORTE_LOGISTICO,
    CD_GRUPO_ITEM,
    CD_SUBGRUPO_ITEM,
    CD_SECAO_ITEM,
    CD_ITEM,
    CD_CONDPAGTO,
    VL_QUANTIDADE,
    VL_VENDA_BRUTA,
    VL_DESCONTO,
    VL_IMPOSTO_TOTAL,
    VL_ISSQN,
    VL_PIS,
    VL_COFINS,
    VL_ICMS,
    VL_VENDA_LIQUIDA,
    VL_CUSTO_TOTAL,
    VL_CUSTO_MATERIAIS,
    VL_CUSTO_REVENDA,
    VL_CUSTO_MPS_DIRETO,
    VL_CUSTO_MPS_INDIRETO,
    VL_CUSTO_MOB,
    VL_CUSTO_GGF,
    VL_MARGEM_BRUTA,
    VL_COMISSAO_TOTAL,
    VL_COMISSAO_VENDEDOR,
    VL_COMISSAO_PARCEIRO,
    VL_COMISSAO_SUPORTE_LOGISTICO,
    VL_MARGEM_LIQUIDA,
    TRIMESTRE,
    SEMESTER,
    MES,
    ANO,
    EMPRESA)
AS
WITH IMPOSTOS
AS (SELECT
       IPN.CD_EMPRESA, IPN.NR_LANCAMENTO, IPN.TP_NOTA, IPN.CD_SERIE, IPN.CD_ITEM,
       SUM(IIF(IP.TP_IMPOSTO = 'I', IPN.VL_IMPOSTO, 0)) VL_ICMS,
       SUM(IIF(IP.TP_IMPOSTO = 'F', IPN.VL_IMPOSTO, 0)) VL_COFINS,
       SUM(IIF(IP.TP_IMPOSTO = 'S', IPN.VL_IMPOSTO, 0)) VL_PIS, SUM(IIF(IP.TP_IMPOSTO = 'Q', IPN.VL_IMPOSTO, 0)) VL_SSQN
    FROM IMPOSTONOTA IPN
    INNER JOIN IMPOSTO IP ON (IP.CD_IMPOSTO = IPN.CD_IMPOSTO)
    GROUP BY IPN.CD_EMPRESA, IPN.NR_LANCAMENTO, IPN.TP_NOTA, IPN.CD_SERIE, IPN.CD_ITEM

),

CENTROCUSTO_NOTA
AS (SELECT
       ITCC.CD_EMPRESA, ITCC.NR_LANCAMENTO, ITCC.TP_NOTA, ITCC.CD_SERIE, ITCC.CD_ITEM, CC.CD_CENTROCUSTO,
       CC.DS_CENTROCUSTO, CC.ST_ATIVO, CC.NR_GRAU, CC.CD_CLASSIFICACAO
    FROM ITEMNOTACC ITCC
    INNER JOIN CENTROCUSTO CC ON (CC.CD_EMPRESA = ITCC.CD_EMPRCENTROCUSTO
                              AND CC.CD_CENTROCUSTO = ITCC.CD_CENTROCUSTO)
    WHERE CC.CD_CENTROCUSTO NOT IN (1006,7005)
    GROUP BY ITCC.CD_EMPRESA, ITCC.NR_LANCAMENTO, ITCC.TP_NOTA, ITCC.CD_SERIE, ITCC.CD_ITEM, CC.CD_CENTROCUSTO, CC.DS_CENTROCUSTO,
    CC.ST_ATIVO, CC.NR_GRAU, CC.CD_CLASSIFICACAO

),

CUSTO_REVENDA
AS (SELECT
       ME.NR_LANCTONOTA, ME.CD_SERIE, ME.TP_NOTA, ME.CD_ITEM, ME.CD_EMPRESA, SUM(ME.VL_ESTOQUE) VL_REVENDA
    FROM MOVESTOQUE ME
    INNER JOIN ITEM I ON (I.CD_ITEM = ME.CD_ITEM)
    WHERE ME.ST_CANCELAMENTO = 'N'
      AND I.CD_GRUPO = 40
      AND ME.TP_DOCUMENTO = 'NF'
      AND ME.NR_LANCTONOTA IS NOT NULL
    GROUP BY ME.NR_LANCTONOTA, ME.CD_SERIE, ME.TP_NOTA, ME.CD_ITEM, ME.CD_EMPRESA

),

CUSTO_PRODUCAO
AS (SELECT
       X.CD_EMPRESA, X.NR_LANCAMENTO, X.CD_SERIE, X.TP_NOTA, COALESCE(IP.CD_ITEM, X.IDSERVICOPNEU) IDSERVICOPNEU,
       SUM(IIF(X.CD_MATERIAPRIMA = 9811, M.VL_ESTOQUE, 0)) VL_DIRETOS,
       SUM(IIF(X.CD_MATERIAPRIMA = 9812, M.VL_ESTOQUE, 0)) VL_INDIRETOS,
       SUM(IIF(X.CD_MATERIAPRIMA = 9813, M.VL_ESTOQUE, 0)) VL_MOB,
       SUM(IIF(X.CD_GRUPO = 50 AND X.DS_OBSERVACAO SIMILAR TO 'Preparação de Banda%|Emborrachamento%', M.VL_ESTOQUE, M2.VL_ESTOQUE)) VL_CUSTO_BANDA
    FROM (SELECT
             N.CD_EMPRESA, N.NR_LANCAMENTO, N.CD_SERIE, N.TP_NOTA, OP.CD_EMPRESA CD_EMPRESA_OP, OP.NR_ORDEMPRODUCAO,
             IOP.CD_MATERIAPRIMA, I.CD_GRUPO, OP.DS_OBSERVACAO, IPP.IDSERVICOPNEU,
             IIF(OP.DS_OBSERVACAO IS NULL AND I.CD_GRUPO = 50, IOP.CD_MATERIAPRIMA, NULL) CD_REPARO

          FROM NOTA N
          LEFT JOIN RETORNA_CHAVEPEDIDO(N.CD_EMPRESA, N.NR_LANCAMENTO, N.TP_NOTA, N.CD_SERIE) CH ON (1 = 1)
          INNER JOIN PLUGORDRECAPPEDIDO P ON (P.CD_EMPRESA = CH.O_CD_EMPRESA
                                           AND P.NR_PEDIDO = CH.O_NR_PEDIDO
                                           AND P.TP_PEDIDO = CH.O_TP_PEDIDO)
          INNER JOIN ORDEMPRODUCAO OP ON (OP.CD_EMPRLOTEPROD = P.CD_EMPRESA
                                      AND OP.NR_LOTEPRODUCAO = P.IDORDEMPRODUCAORECAP
                                      AND OP.TP_PRODUCAO = 'C')
          INNER JOIN ITEMORDEMPROD IOP ON (IOP.CD_EMPRESA = OP.CD_EMPRESA
                                       AND IOP.NR_ORDEMPRODUCAO = OP.NR_ORDEMPRODUCAO
                                       AND IOP.TP_DESPESA = 'M')
          INNER JOIN ITEM I ON (I.CD_ITEM = IOP.CD_MATERIAPRIMA)
          INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = P.IDORDEMPRODUCAORECAP)
          INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
          WHERE N.ST_NOTA = 'V'
            AND N.DT_EMISSAO > '31.12.2023'
            AND (IOP.CD_MATERIAPRIMA IN (9811, 9812, 9813) OR I.CD_GRUPO = 50)
          GROUP BY N.CD_EMPRESA, N.NR_LANCAMENTO, N.CD_SERIE, N.TP_NOTA, OP.CD_EMPRESA, OP.NR_ORDEMPRODUCAO, IOP.CD_MATERIAPRIMA, I.CD_GRUPO,
          OP.DS_OBSERVACAO, IPP.IDSERVICOPNEU, CD_REPARO

    ) X
    INNER JOIN MOVESTOQUE M ON (M.CD_EMPRORDEMPROD = X.CD_EMPRESA_OP
                           AND M.NR_ORDEMPRODUCAO = X.NR_ORDEMPRODUCAO
                           AND M.CD_ITEM = X.CD_MATERIAPRIMA
                           AND M.ST_CANCELAMENTO = 'N'
                           AND M.TP_DOCUMENTO = 'PR')
    LEFT JOIN ITEMPRODUCAO IP ON (IP.CD_EMPRESA = X.CD_EMPRESA
                              AND IP.CD_MATERIAPRIMA = X.CD_REPARO)
    LEFT JOIN MOVESTOQUE M2 ON (M2.CD_EMPRORDEMPROD = X.CD_EMPRESA_OP
                           AND M2.NR_ORDEMPRODUCAO = X.NR_ORDEMPRODUCAO
                           AND M2.CD_ITEM = X.CD_REPARO
                           AND M2.ST_CANCELAMENTO = 'N'
                           AND M2.TP_DOCUMENTO = 'PR')
    GROUP BY X.CD_EMPRESA, X.NR_LANCAMENTO, X.CD_SERIE, X.TP_NOTA, IDSERVICOPNEU

)
SELECT
   DATETOSTR(N.DT_EMISSAO, '%d/%m/%Y') NF_DATA, COALESCE(N.NR_NOTAFISCAL, N.NR_NOTAFOR) NF_NUMERO, N.CD_SERIE NF_SERIE, N.TP_NOTA NF_TIPO, N.NR_LANCAMENTO NF_LANCAMENTO, '1000' CD_EMPRESA,
   E.CD_EMPRESA CD_FILIAL, MU.sg_estado CD_ESTADO, CCN.CD_CLASSIFICACAO CD_CENTRO_RESULTADO, MU.CD_MUNICIPIO, PC.CD_PESSOA CD_CLIENTE,
   LIST(IIF(ITV.CD_TIPO = 1, ITV.CD_VENDEDOR, ''), '') CD_VENDEDOR,
   LIST(IIF(ITV.CD_TIPO = 2, ITV.CD_VENDEDOR, ''), '') CD_PARCEIRO,
   LIST(IIF(ITV.CD_TIPO = 3, ITV.CD_VENDEDOR, ''), '') CD_SUPORTE_LOGISTICO,
   I.CD_GRUPO CD_GRUPO_ITEM, I.CD_SUBGRUPO CD_SUBGRUPO_ITEM, I.CD_SECAO CD_SECAO_ITEM, I.CD_ITEM, N.CD_CONDPAGTO,


   IIF(N.TP_NOTA = 'S', IT.QT_ITEMNOTA, IT.QT_ITEMNOTA * -1) VL_QUANTIDADE,
   IIF(N.TP_NOTA = 'S', IT.VL_TOTAL, IT.VL_TOTAL * -1) VL_VENDA_BRUTA,
  -- IIF(N.TP_NOTA = 'S', IT.VL_LIQUIDO, IT.VL_LIQUIDO * -1) VL_NOTA_LIQUIDA,
   IIF(N.TP_NOTA = 'S', COALESCE(IT.VL_DESCONTO, 0), COALESCE(IT.VL_DESCONTO, 0) * -1) VL_DESCONTO,


     CASE N.TP_NOTA
     WHEN 'S' THEN (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0))
     ELSE (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0)) * -1
   END VL_IMPOSTO_TOTAL,


   IIF(N.TP_NOTA = 'S', COALESCE(IP.VL_SSQN, 0), COALESCE(IP.VL_SSQN, 0) * -1) VL_ISSQN,
   IIF(N.TP_NOTA = 'S', COALESCE(IP.VL_PIS, 0), COALESCE(IP.VL_PIS, 0) * -1) VL_PIS,
   IIF(N.TP_NOTA = 'S', COALESCE(IP.VL_COFINS, 0), COALESCE(IP.VL_COFINS, 0) * -1) VL_COFINS,
   IIF(N.TP_NOTA = 'S', COALESCE(IP.VL_ICMS, 0), COALESCE(IP.VL_ICMS, 0) * -1) VL_ICMS,

     CASE N.TP_NOTA
      WHEN 'S' THEN (IT.VL_TOTAL - COALESCE(IT.VL_DESCONTO, 0) - (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0)))
      ELSE (IT.VL_TOTAL - COALESCE(IT.VL_DESCONTO, 0) - (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0))) * -1
   END VL_VENDA_LIQUIDA,

   CASE N.TP_NOTA
      WHEN 'S' THEN ((COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0)) + COALESCE(CP.VL_MOB, 0) + COALESCE(CP.VL_INDIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0))
      ELSE ((COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0)) + COALESCE(CP.VL_MOB, 0) + COALESCE(CP.VL_INDIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0)) * -1
   END VL_CUSTO_TOTAL,

      CASE N.TP_NOTA
      WHEN 'S' THEN (COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0))
      ELSE (COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0)) * -1
   END VL_CUSTO_MATERIAIS,

      IIF(N.TP_NOTA = 'S', COALESCE(CR.VL_REVENDA, 0), COALESCE(CR.VL_REVENDA, 0) * -1) VL_CUSTO_REVENDA,
   COALESCE(CP.VL_CUSTO_BANDA,0) VL_CUSTO_MPS_DIRETO,
   COALESCE(CP.VL_DIRETOS, 0) VL_CUSTO_MPS_INDIRETO,
   COALESCE(CP.VL_MOB, 0) VL_CUSTO_MOB,
   COALESCE(CP.VL_INDIRETOS, 0) VL_CUSTO_GGF,

        
   CASE N.TP_NOTA
      WHEN 'S' THEN ((IT.VL_TOTAL - COALESCE(IT.VL_DESCONTO, 0) - (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0)))) -
                    ((COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0)) + COALESCE(CP.VL_MOB, 0) + COALESCE(CP.VL_INDIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0))
      ELSE ((IT.VL_TOTAL - COALESCE(IT.VL_DESCONTO, 0) - (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0))) -
                    ((COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0)) + COALESCE(CP.VL_MOB, 0) + COALESCE(CP.VL_INDIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0))) * -1
   END VL_MARGEM_BRUTA,

   CASE N.TP_NOTA
      WHEN 'S' THEN (SUM(IIF(ITV.CD_TIPO = 1, COALESCE(ITV.VL_COMISSAO,0), 0)) + SUM(IIF(ITV.CD_TIPO = 2, COALESCE(ITV.VL_COMISSAO,0), 0)) + SUM(IIF(ITV.CD_TIPO = 3, COALESCE(ITV.VL_COMISSAO,0), 0)))
               ELSE (SUM(IIF(ITV.CD_TIPO = 1, COALESCE(ITV.VL_COMISSAO,0), 0)) + SUM(IIF(ITV.CD_TIPO = 2, COALESCE(ITV.VL_COMISSAO,0), 0)) + SUM(IIF(ITV.CD_TIPO = 3, COALESCE(ITV.VL_COMISSAO,0), 0))) * -1
   END VL_COMISSAO_TOTAL,


   SUM(CASE
          WHEN N.TP_NOTA = 'S' AND ITV.CD_TIPO = 1 THEN COALESCE(ITV.VL_COMISSAO,0)
          WHEN N.TP_NOTA = 'E' AND ITV.CD_TIPO = 1 THEN COALESCE(ITV.VL_COMISSAO,0) * -1
          ELSE 0
       END) VL_COMISSAO_VENDEDOR,

   SUM(CASE
          WHEN N.TP_NOTA = 'S' AND ITV.CD_TIPO = 2 THEN COALESCE(ITV.VL_COMISSAO,0)
          WHEN N.TP_NOTA = 'E' AND ITV.CD_TIPO = 2 THEN COALESCE(ITV.VL_COMISSAO,0) * -1
          ELSE 0
       END) VL_COMISSAO_PARCEIRO,

   SUM(CASE
         WHEN N.TP_NOTA = 'S' AND ITV.CD_TIPO = 3 THEN COALESCE(ITV.VL_COMISSAO,0)
         WHEN N.TP_NOTA = 'E' AND ITV.CD_TIPO = 3 THEN COALESCE(ITV.VL_COMISSAO,0) * -1
         ELSE 0
       END) VL_COMISSAO_SUPORTE_LOGISTICO,
    
    CASE N.TP_NOTA
      WHEN 'S' THEN ((IT.VL_TOTAL - COALESCE(IT.VL_DESCONTO, 0) - (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0))) -
                      ((COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0)) + COALESCE(CP.VL_MOB, 0) + COALESCE(CP.VL_INDIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0))) -
                          (SUM(IIF(ITV.CD_TIPO = 1, COALESCE(ITV.VL_COMISSAO,0), 0)) + SUM(IIF(ITV.CD_TIPO = 2, COALESCE(ITV.VL_COMISSAO,0), 0)) + SUM(IIF(ITV.CD_TIPO = 3, COALESCE(ITV.VL_COMISSAO,0), 0)))
      ELSE ((IT.VL_TOTAL - COALESCE(IT.VL_DESCONTO, 0) - (COALESCE(IP.VL_ICMS, 0) + COALESCE(IP.VL_COFINS, 0) + COALESCE(IP.VL_PIS, 0) + COALESCE(IP.VL_SSQN, 0))) -
                      ((COALESCE(CR.VL_REVENDA, 0) + COALESCE(CP.VL_DIRETOS, 0)) + COALESCE(CP.VL_MOB, 0) + COALESCE(CP.VL_INDIRETOS, 0) + COALESCE(CP.VL_CUSTO_BANDA,0))) * -1 -
                          ((SUM(IIF(ITV.CD_TIPO = 1, COALESCE(ITV.VL_COMISSAO,0), 0)) +
                            SUM(IIF(ITV.CD_TIPO = 2, COALESCE(ITV.VL_COMISSAO,0), 0)) +
                            SUM(IIF(ITV.CD_TIPO = 3, COALESCE(ITV.VL_COMISSAO,0), 0))) * -1)

   END VL_MARGEM_LIQUIDA,

    COALESCE(
   IIF ((EXTRACT(MONTH FROM N.DT_EMISSAO) IN (1,2,3)), 1, NULL),
   IIF ((EXTRACT(MONTH FROM N.DT_EMISSAO) IN (4,5,6)), 2, NULL),
   IIF ((EXTRACT(MONTH FROM N.DT_EMISSAO) IN (7,8,9)), 3, NULL),
   IIF ((EXTRACT(MONTH FROM N.DT_EMISSAO) IN (10,11,12)), 4, NULL)
    ) TRIMESTRE,

   IIF ((EXTRACT(MONTH FROM N.DT_EMISSAO) < 7), 1, 2) SEMESTER,

   EXTRACT(MONTH FROM N.DT_EMISSAO) MES,
   EXTRACT(YEAR FROM N.DT_EMISSAO) ANO,
   'RENOVADORA DE PNEUS HOFF SA' EMPRESA

FROM NOTA N
INNER JOIN ITEMNOTA IT ON (IT.CD_EMPRESA = N.CD_EMPRESA
                       AND IT.NR_LANCAMENTO = N.NR_LANCAMENTO
                       AND IT.TP_NOTA = N.TP_NOTA
                       AND IT.CD_SERIE = N.CD_SERIE)
INNER JOIN ITEM I ON (I.CD_ITEM = IT.CD_ITEM)
LEFT JOIN ITEMNOTAVENDEDOR ITV ON (ITV.CD_EMPRESA = IT.CD_EMPRESA
                               AND ITV.NR_LANCAMENTO = IT.NR_LANCAMENTO
                               AND ITV.TP_NOTA = IT.TP_NOTA
                               AND ITV.CD_SERIE = IT.CD_SERIE
                               AND ITV.CD_ITEM = IT.CD_ITEM)
INNER JOIN MOVIMENTACAO M ON (M.CD_MOVIMENTACAO = IT.CD_MOVIMENTACAO)
INNER JOIN EMPRESA E ON (E.CD_EMPRESA = N.CD_EMPRESA)
INNER JOIN PESSOA PC ON (PC.CD_PESSOA = N.CD_PESSOA)
INNER JOIN ENDERECOPESSOA EP ON (EP.CD_PESSOA = PC.CD_PESSOA
                             AND EP.CD_ENDERECO = 1)
INNER JOIN MUNICIPIO MU ON (MU.CD_MUNICIPIO = EP.CD_MUNICIPIO)
LEFT JOIN PESSOA PV ON (PV.CD_PESSOA = ITV.CD_VENDEDOR)
LEFT JOIN IMPOSTOS IP ON (IP.CD_EMPRESA = IT.CD_EMPRESA
                       AND IP.NR_LANCAMENTO = IT.NR_LANCAMENTO
                       AND IP.TP_NOTA = IT.TP_NOTA
                       AND IP.CD_SERIE = IT.CD_SERIE
                       AND IP.CD_ITEM = IT.CD_ITEM)
LEFT JOIN CENTROCUSTO_NOTA CCN ON (CCN.CD_EMPRESA = IT.CD_EMPRESA
                               AND CCN.NR_LANCAMENTO = IT.NR_LANCAMENTO
                               AND CCN.TP_NOTA = IT.TP_NOTA
                               AND CCN.CD_SERIE = IT.CD_SERIE
                                   )
LEFT JOIN CUSTO_REVENDA CR ON (CR.NR_LANCTONOTA = IT.NR_LANCAMENTO
                           AND CR.CD_SERIE = IT.CD_SERIE
                           AND CR.TP_NOTA = IT.TP_NOTA
                           AND CR.CD_ITEM = IT.CD_ITEM
                           AND CR.CD_EMPRESA = IT.CD_EMPRESA)
LEFT JOIN CUSTO_PRODUCAO CP ON (CP.CD_EMPRESA = N.CD_EMPRESA
                             AND CP.NR_LANCAMENTO = N.NR_LANCAMENTO
                             AND CP.CD_SERIE = N.CD_SERIE
                             AND CP.TP_NOTA = N.TP_NOTA
                             AND CP.IDSERVICOPNEU = IT.CD_ITEM)
WHERE N.ST_NOTA = 'V'
  AND (N.TP_NOTA = 'S' OR N.TP_NOTA = 'E' AND M.ST_DEVOLUCAO = 'D')
  AND N.CD_EMPRESA NOT IN (2000, 4000)
  AND M.CD_TIPOCONTA IS NOT NULL
  AND M.ST_RECEITA = 'S'


GROUP BY
CD_FILIAL, NF_LANCAMENTO, NF_NUMERO, NF_SERIE,  NF_TIPO, NF_DATA, CD_CLIENTE,
CD_MUNICIPIO, CD_ESTADO, CD_CONDPAGTO, CD_ITEM,
CD_GRUPO_ITEM, CD_SUBGRUPO_ITEM, CD_SECAO_ITEM,
VL_QUANTIDADE, VL_VENDA_BRUTA, VL_DESCONTO, VL_ICMS,
VL_COFINS, VL_PIS, VL_ISSQN, CD_CENTRO_RESULTADO, VL_CUSTO_REVENDA, VL_CUSTO_MPS_INDIRETO,
VL_CUSTO_GGF, VL_CUSTO_MOB, VL_CUSTO_MPS_DIRETO,
N.TP_NOTA, IT.VL_TOTAL, IT.VL_DESCONTO, IP.VL_ICMS , IP.VL_COFINS , IP.VL_PIS,
IP.VL_SSQN, CR.VL_REVENDA, CP.VL_DIRETOS, CP.VL_MOB, CP.VL_INDIRETOS, CP.VL_CUSTO_BANDA,
VL_IMPOSTO_TOTAL, VL_VENDA_LIQUIDA, VL_CUSTO_MATERIAIS, VL_CUSTO_TOTAL, VL_MARGEM_BRUTA,
MES, ANO, SEMESTER, TRIMESTRE

ORDER BY N.NR_LANCAMENTO
;




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON VIEW_SALESGRID TO HOFF WITH GRANT OPTION;

/* Privileges of views */
GRANT SELECT ON CENTROCUSTO TO VIEW VIEW_SALESGRID;
GRANT SELECT ON EMPRESA TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ENDERECOPESSOA TO VIEW VIEW_SALESGRID;
GRANT SELECT ON IMPOSTO TO VIEW VIEW_SALESGRID;
GRANT SELECT ON IMPOSTONOTA TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ITEM TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ITEMNOTA TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ITEMNOTACC TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ITEMNOTAVENDEDOR TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ITEMORDEMPROD TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ITEMPEDIDOPNEU TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ITEMPRODUCAO TO VIEW VIEW_SALESGRID;
GRANT SELECT ON MOVESTOQUE TO VIEW VIEW_SALESGRID;
GRANT SELECT ON MOVIMENTACAO TO VIEW VIEW_SALESGRID;
GRANT SELECT ON MUNICIPIO TO VIEW VIEW_SALESGRID;
GRANT SELECT ON NOTA TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ORDEMPRODUCAO TO VIEW VIEW_SALESGRID;
GRANT SELECT ON ORDEMPRODUCAORECAP TO VIEW VIEW_SALESGRID;
GRANT SELECT ON PESSOA TO VIEW VIEW_SALESGRID;
GRANT SELECT ON PLUGORDRECAPPEDIDO TO VIEW VIEW_SALESGRID;
GRANT EXECUTE ON PROCEDURE RETORNA_CHAVEPEDIDO TO VIEW VIEW_SALESGRID;
GRANT EXECUTE ON FUNCTION DATETOSTR TO VIEW VIEW_SALESGRID;